/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master2016;

import java.util.Map;
import org.apache.storm.task.OutputCollector;
import org.apache.storm.task.TopologyContext;
import org.apache.storm.topology.OutputFieldsDeclarer;
import org.apache.storm.topology.base.BaseRichBolt;
import org.apache.storm.tuple.Tuple;

/**
 * Bolt Filter to catch only the languages needed.
 *
 * @authors Alvaro Feal; Gorka Revilla
 * @version 0.1
 * @since 07-11-2016
 */
public class LangBolt extends BaseRichBolt {

	/**
	 * AutoGenerated
	 */
	private static final long serialVersionUID = 5259021092740992581L;
	
	
	private final String lang;

	public LangBolt(String lang) {
		this.lang = lang;
	}

	public void prepare(Map stormConf, TopologyContext context, OutputCollector collector) {
		// NOTHING TO PREPARE

	}

	public void execute(Tuple input) {
		if (Top3App.DEBUG)
			System.out.println("LangBolt"+this.lang+"=> Received: " + input.getValues());

		String tupleLang = input.getValueByField(Topology.LANGUAGE_FIELDNAME).toString();
		String tupleHashtag = input.getValueByField(Topology.HASHTAG_FIELDNAME).toString();

		if (tupleLang.equals(lang)) {

			if (Top3App.DEBUG)
				System.out.println("LangBolt"+this.lang+"=> Language: " + tupleLang + " Hashtag: "+tupleHashtag);

		}
	}

	public void declareOutputFields(OutputFieldsDeclarer declarer) {
		// NO OUTPUTS

	}

}
